name: tlar
description: TLAR app for access control.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.3.0
  cloud_firestore: ^0.9.9
  firebase_auth: ^0.8.2
  google_sign_in: ^4.0.1+1
  date_format: ^1.0.6
  location: ^1.4.1
  font_awesome_flutter: ^8.4.0
  fancy_bottom_navigation: ^0.3.2
  qr_flutter: ^2.0.0
  datetime_picker_formfield: ^0.1.8
  rflutter_alert: ^1.0.2
  firebase_messaging: ^4.0.0+1
  country_code_picker: ^1.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/TLAR-Logos.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/background.png
  - assets/parking-background.png
  - assets/tlar-logo.png
  - assets/tlar-logo-transp.png
  - assets/img/google.png
  - assets/img/noNotification.png
  - assets/img/noInvitation.png
  - assets/img/notmessage.png
  - assets/icon/truck.png
  - assets/icon/chat.png
  - assets/icon/notification.png
  - assets/icon/callcenter.png
  - assets/icon/setting.png
  - assets/icon/aboutapp.png
  - assets/icon/shopping-cart.png
  - assets/icon/message.png
  - assets/icon/creditAcount.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Glacial Indifference
    fonts:
    - asset: fonts/GlacialIndifference-Regular.otf
    - asset: fonts/GlacialIndifference-Italic.otf
    - asset: fonts/GlacialIndifference-Bold.otf
      style: normal
  - family: League Spartan
    fonts:
    - asset: fonts/LeagueSpartan-Bold.otf
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
